apiVersion: apps/v1
kind: Deployment
metadata:
  name: moviebooking-frontend
  labels:
    app: moviebooking-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: moviebooking-frontend
  template:
    metadata:
      labels:
        app: moviebooking-frontend
    spec:
      containers:
        - name: frontend
          image: rishi272004/moviebooking-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
