apiVersion: v1
kind: Service
metadata:
  name: moviebooking-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: moviebooking-frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
